// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdznQBNgZTOipPfjHwX5-_GLDdwYMwwJs',
    appId: '1:1035946120278:web:72dab60742745249f957f7',
    messagingSenderId: '1035946120278',
    projectId: 'notes-ab4b1',
    authDomain: 'notes-ab4b1.firebaseapp.com',
    storageBucket: 'notes-ab4b1.firebasestorage.app',
    measurementId: 'G-8LXCBFGCCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnU9439oaCBiaCVqeMMtJ9IycJCTdF004',
    appId: '1:1035946120278:android:feefd72f9b0f9346f957f7',
    messagingSenderId: '1035946120278',
    projectId: 'notes-ab4b1',
    storageBucket: 'notes-ab4b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHRn6CEP4z1ctdSLcuxVqbVbFl3lpSjE',
    appId: '1:1035946120278:ios:1ebe27bb4f5accc0f957f7',
    messagingSenderId: '1035946120278',
    projectId: 'notes-ab4b1',
    storageBucket: 'notes-ab4b1.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHRn6CEP4z1ctdSLcuxVqbVbFl3lpSjE',
    appId: '1:1035946120278:ios:1ebe27bb4f5accc0f957f7',
    messagingSenderId: '1035946120278',
    projectId: 'notes-ab4b1',
    storageBucket: 'notes-ab4b1.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdznQBNgZTOipPfjHwX5-_GLDdwYMwwJs',
    appId: '1:1035946120278:web:7cc1bb107cc3d4eff957f7',
    messagingSenderId: '1035946120278',
    projectId: 'notes-ab4b1',
    authDomain: 'notes-ab4b1.firebaseapp.com',
    storageBucket: 'notes-ab4b1.firebasestorage.app',
    measurementId: 'G-GK847PEWRL',
  );
}
